version: "3.8"
services:
  db:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_USER=root"
      - "POSTGRES_DB=monitoring"
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: "server /data --console-address \":9001\""

  manager:
    image: monitoring-manager:dev
    depends_on:
      - db
      - minio
    environment:
      - "AWS_REGION=us-west-1"
    ports:
      - "8080:8080"
      - "8081:8081"