name: Scala CI

on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  Test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Setup scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11

      - name: Restore cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/Dependencies.scala') }}

      - name: Initialize project
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: "sbt initialize"
    
      - name: Run unit tests
        run: "sbt test"

      - name: Run integration tests
        run: "sbt it:test"

  Build_image:
    name: "Build Image"
    runs-on: ubuntu-20.04
    env:
      IMAGE: monitoring-manager # name of the built image
      REGISTRY: hydrosphere
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11
      
      - name: Restore cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/Dependencies.scala') }}

      - name: Initialize project
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: "sbt initialize"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-       
      
      - name: Build docker image
        run: "sbt docker:publishLocal"

      - name: Retag image
        run: "docker tag ${{ env.IMAGE }}:dev ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest"

  Docs:
    name: "Generate Docs"
    runs-on: ubuntu-20.04
    env:
      IMAGE: monitoring-manager # name of the built image
      REGISTRY: hydrosphere
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11
      
      - name: Restore cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/Dependencies.scala') }}

      - name: Initialize project
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: "sbt initialize"

      - name: Generate Docs
        run: "sbt openapi"

      - name: Commit Docs Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update openapi.yaml and config.md"
