name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup scala
      uses: olafurpg/setup-scala@v10
      with:
       java-version: adopt@1.11

    - name: Restore cache
      uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/Dependencies.scala') }}

    - name: Initialize project
      if: steps.restore-cache.outputs.cache-hit != 'true'
      run: "sbt initialize"
  
    - name: Run tests
      run: "sbt test"
